export PATH=$HOME/bin:$HOME/.local/bin:$HOME/.flutter/bin:$PATH
export TERM="xterm-256color"
export LANG=en_US.UTF-8

if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

source $HOME/.aliases

### Added by Zinit's installer
if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
    print -P "%F{33} %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
    command mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
    command git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git" && \
        print -P "%F{33} %F{34}Installation successful.%f%b" || \
        print -P "%F{160} The clone has failed.%f%b"
fi

source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
    zdharma-continuum/zinit-annex-as-monitor \
    zdharma-continuum/zinit-annex-bin-gem-node \
    zdharma-continuum/zinit-annex-patch-dl \
    zdharma-continuum/zinit-annex-rust

### End of Zinit's installer chunk

zinit snippet OMZP::asdf
zinit snippet OMZP::git
# zinit snippet OMZP::asdf
zinit snippet OMZP::archlinux
zinit snippet OMZP::brew
zinit snippet OMZP::composer
zinit snippet OMZP::colored-man-pages
zinit snippet OMZP::extract
zinit snippet OMZP::gradle
zinit snippet OMZP::node
zinit snippet OMZP::npm
zinit snippet OMZP::nvm
zinit snippet OMZP::rbenv
zinit snippet OMZP::sudo
zinit snippet OMZP::direnv
zinit snippet OMZP::docker
zinit snippet OMZP::docker-compose
zinit snippet OMZP::golang
zinit snippet OMZP::pip
zinit snippet OMZP::history
zinit snippet OMZP::vagrant

zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-autosuggestions
zinit light zsh-users/zsh-syntax-highlighting
zinit light zkuzmic/which-jspm

zinit ice as"command" from"gh-r" \
          atclone"./starship init zsh > init.zsh; ./starship completions zsh > _starship" \
          atpull"%atclone" src"init.zsh"
zinit light starship/starship

# eval "$(starship init zsh)"

# pnpm
export PNPM_HOME="/home/thilo/.local/share/pnpm"
export PATH="$PNPM_HOME:$PATH"

# bun completions
[ -s "/home/thilo/.bun/_bun" ] && source "/home/thilo/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

export DENO_INSTALL="/home/thilo/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"
