# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-0b8e9c8a-692e-45be-ad20-cda9df7092ea";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-0b8e9c8a-692e-45be-ad20-cda9df7092ea".device = "/dev/disk/by-uuid/0b8e9c8a-692e-45be-ad20-cda9df7092ea";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3D57-E326";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };


  fileSystems = {
    "/data" = {
      device = "/dev/disk/by-uuid/a13a2cfa-12af-463d-ae5c-d46c881fcdd6";
      fsType = "btrfs";
      options = [ "nofail" ];
    };
  };

  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
